export const countryCodes = [
  { code: "+507", country: "PA", label: "Panamá +507" },
  { code: "+1", country: "US", label: "USA/CAN +1" },
  { code: "+52", country: "MX", label: "México +52" },
  { code: "+57", country: "CO", label: "Colombia +57" },
  { code: "+58", country: "VE", label: "Venezuela +58" },
  { code: "+506", country: "CR", label: "Costa Rica +506" },
  { code: "+503", country: "SV", label: "El Salvador +503" },
  { code: "+502", country: "GT", label: "Guatemala +502" },
  { code: "+504", country: "HN", label: "Honduras +504" },
  { code: "+505", country: "NI", label: "Nicaragua +505" },
  { code: "+593", country: "EC", label: "Ecuador +593" },
  { code: "+51", country: "PE", label: "Perú +51" },
  { code: "+56", country: "CL", label: "Chile +56" },
  { code: "+54", country: "AR", label: "Argentina +54" },
  { code: "+55", country: "BR", label: "Brasil +55" },
  { code: "+34", country: "ES", label: "España +34" },
  { code: "+591", country: "BO", label: "Bolivia +591" },
  { code: "+595", country: "PY", label: "Paraguay +595" },
  { code: "+598", country: "UY", label: "Uruguay +598" },
  { code: "+53", country: "CU", label: "Cuba +53" },
  { code: "+1809", country: "DO", label: "Rep. Dom. +1809" },
  { code: "+44", country: "GB", label: "Reino Unido +44" },
  { code: "+33", country: "FR", label: "Francia +33" },
  { code: "+49", country: "DE", label: "Alemania +49" },
  { code: "+39", country: "IT", label: "Italia +39" },
];
